# Changes here will be overwritten by Copier
AnswerStrategy: minimum
Authors: Mikhail Mikhasenko <mikhail.mikhasenko@gmail.com>
Indentation: 4
JuliaMinVersion: "1.3"
License: MIT
LicenseCopyrightHolders: Mikhail Mikhasenko
PackageName: FourVectors
PackageOwner: mmikhasenko
PackageUUID: b122eb78-8380-428a-b8c8-584a022ae8b6
_commit: v0.10.1
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
